Docker additions
Virtana/image-selection-interface pull request #29
Opened 2023-02-03 18:55 UTC by DAA2310

2023-02-03 19:04 UTC, DAA2310 commented
NOTE merge into deployed react branch, not main. Not sure whether this matters, can change if necessary.

2023-02-06 13:00 UTC, chris24sahadeo requested changes

2023-02-06 16:06 UTC, chris24sahadeo requested changes

2023-02-06 16:06 UTC, chris24sahadeo commented on docker/build_zipdev_container.sh
> +             --build-arg UNAME=$(whoami) \
Add a comment on this file, explaining that a build is only valid for the user that has created the build. This prevents other users from using this image and the ECR workflow. You can add a JIRA ticket and put the ticket code in the comment, use syntax: TODO(david@): [PDO-XYZ] so others reading the code know who to contact for more context.

2023-02-06 17:58 UTC, DAA2310 commented on docker/zipline_dev.Dockerfile
> +        build-essential \
Saw it in example dockerfile for nodejs app so I just copied. Removed and seems to be okay.

2023-02-06 18:04 UTC, chris24sahadeo approved these changes

2023-02-06 18:28 UTC, merged

2023-02-20 15:39 UTC, chris24sahadeo commented on docker/zipline_dev.Dockerfile
> +ENV DEBIAN_FRONTEND=noninteractive
@DAA2310 I think a simpler solution to fix the file permissions issue would've been to run the:
```
sudo chown -R $USER $PWD
```
command on the host, rather than all the extra infra to establish a user. 
Think about running docker in prod, where the intention is to always run as root anyway.